### PR TITLE
Fix issue with crash on Apple TV devices.

### LINKED ISSUE #177: Crash on Apple TV device
**Describe the bug**
I am getting an app crash when using the SDK on a physical Apple TV device.  I get the following error when the SDK is attempting to create the CrowdinFolder for the translation files:

> Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=513 "You don't have permission to save the file "Crowdin" in the folder "<Bundle ID>.Crowdin"."

Note that this does not happen on the Apple TV simulator in Xcode, only a physical device.

**To Reproduce**
1. Build to a physical Apple TV device
2. The app crashes after starting the CrowdinSDK

**Expected behavior**
My understanding is that storing data on an Apple TV is not available outside of the cache directory, and when the SDK attempts to create a folder in the documents directory, the FileManager throws an exception.  

**Screenshots**
Screen Shot 2022-02-22 at 6 49 22 PM

**Smartphone (please complete the following information):**
 - Device: Apple TV 4K (2nd generation)
 - OS: tvOS 15.3

**Additional context**
I was able to avoid the crash by changing DocumentsFolder.documentsPath from:
`static let documentsPath = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]`
to:
`static let documentsPath = NSSearchPathForDirectoriesInDomains(.cachesDirectory, .userDomainMask, true)[0]`
but I am not aware if this will have any performance implications.

### PR DESCRIPTION
**Pull request by serhii-londar**
Used Application Support folder for storing crowding files.  If the Application Support folder is not available Caches folder will be used.

Closes #177

### CODE REVIEW

File: Example/AppleReminders/SceneDelegate.swift [hunk 1]
```diff
@@ -15,8 +15,8 @@ class SceneDelegate: UIResponder, UIWindowSceneDelegate {
     
     // MARK: - Configuration
     
-    private let distributionHash = "your_distribution_hash"
-    private let sourceLanguage = "your_source_language"
+    private let distributionHash = "972b2fc38ef7ac1fb442228106i"
```
Comment (andrii-bodnar) [inline Example/AppleReminders/SceneDelegate.swift:18]: rollback
